# To Display Welcome message
http://localhost:8080

# To Get all boards
http://localhost:8080/boards

# To Get all Single contact
http://localhost:8080/boards/65a2c625be1b15c2fff2dc78

# To open swagger
http://localhost:8080/api-docs

# My Published link that return welcome message
https://contacts-api-ml00.onrender.com

# My Production link that returns all boards
https://contacts-api-ml00.onrender.com

# My Production link that returns board by Id
https://contacts-api-ml00.onrender.com