# To Display Welcome message
http://localhost:8080

# To Get all contacts
http://localhost:8080/contacts

# To Get all Single contact
http://localhost:8080/contacts/65a2c625be1b15c2fff2dc78

# To open swagger
http://localhost:8080/api-docs

# My Published link that return welcome message
https://contacts-api-ml00.onrender.com

# My Production link that returns all contacts
https://contacts-api-ml00.onrender.com



# My Production link that returns contact by Id
https://contacts-api-ml00.onrender.com